# Generated by Django 2.0.13 on 2020-01-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tilte',
            new_name='title',
        ),
    ]
